name: schwifty-markdown # you probably want to 'snapcraft register <name>'
version: '1.3.4' # just for humans, typically '1.2+git' or '1.3.2'
summary: Markdown to HTML with graph charts, yUML and PlantUML support
description: |
  Convert Markdown documents to HTML on the fly, including yUML and
  PlantUML diagrams and graph charts rendering.

grade: devel # must be 'stable' to release into candidate/stable channels
confinement: devmode # use 'strict' once you have the right plugs and slots

apps:
  schwifty-markdown:
    command: bin/schwifty

parts:
  webserver:
    plugin: nodejs
    source: .
    node-engine: 8.9.1
    # node-package-manager: yarn
