on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - "v*" # Push events to matching v*, i.e. v1.0, v20.15.10

name: Create Release

jobs:
  build:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install GH Actions toolkit
        run: npm install @actions/core --no-save
      - name: Read release info
        run: >
          node -e 'const core = require("@actions/core"); const { join } =
          require("path"); const { readFileSync } = require("fs"); const {
          version } = require(join(process.env.GITHUB_WORKSPACE,
          "package.json")); const tag = version.match(/alpha|beta|rc/); const [,
          changes] = readFileSync(join(process.env.GITHUB_WORKSPACE,
          "CHANGELOG.md"), "utf8").split("\n### "); core.setOutput("VERSION",
          version); core.setOutput("RELEASE_NOTES",
          changes.substring(changes.indexOf("\n")));
          core.setOutput("IS_PRE_RELEASE", !!tag); core.setOutput("NPM_FLAGS",
          tag ? `--tag ${tag[0]}` : "--dry-run")'
        id: release_info
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ${{ steps.release_info.outputs.RELEASE_NOTES }}
          draft: true
          prerelease: ${{ steps.release_info.outputs.IS_PRE_RELEASE }}
      - name: Publish to NPM
        id: publish
        run: npm publish ${{ steps.release_info.outputs.NPM_FLAGS }}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
